<a href="https://colab.research.google.com/github/mohit-kumar396/Diabetes-Prediction-ML/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Numpy**

#**NumPy stands for Numerical Python. It is a Python library used for working with numbers and arrays — very fast and efficient compared to normal Python lists.**


In [2]:
import numpy as np #alias -> np

In [3]:
arr = np.array([[1,2,3],[4,5,6]])
arr
# np.array() ka use Python list/sequence ko array mein convert/create karne ke liye hota hai
# Syntax:-
# np.array(OBJECT,dtype)
# Here OBJECT  may be list, tuples, nested sequence
# type(arr) array ka data structure/type batata hai which numpy.ndarray:
# arr.dtype shows array ke elements ka data type batata hai:
# # Note: In NumPy, we commonly say "array" to mean a NumPy array.

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
# dimensions and shape of an array
#Dimension = how many levels deep the array is (1D, 2D, 3D...)
#checked using .ndim
#Shape = how many elements are in each dimension (rows × columns)
#checked using .shape
arr.ndim

2

In [5]:
arr =np.array([34])
arr
arr.shape
arr.ndim

1

In [6]:
a = np.array([[[]]])
a.shape


(1, 1, 0)

In [7]:
range = np.arange(1,10, 2) #start, stop, step
# step is optional like np.arange(1,10)
# You can also omit start only you can write np.arange(stop) but stop is exclusive
# np.arange() ka use given range ke andar evenly spaced values ka NumPy array create karne ke liye hota hai.
# Syntax :-
# np.arange(start, stop, step)

In [8]:
range

array([1, 3, 5, 7, 9])

#**linspace**
#**linspace = linearly spaced numbers**
#**It creates a numpy array with evenly spaced numbers between a start and end value.**

In [9]:
# Syntax :-
# np.linspace(start, stop, num) here num= number of values
# By default, stop is included — unlike np.arange()

In [10]:
arr = np.linspace(0,1,10) #start, stop, number of values
arr


array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

#**logspace = logarithmically spaced numbers**

#**It creates a NumPy array of numbers that are evenly spaced on a logarithmic scale between a start and stop exponent**


In [11]:
# Syntax :-
# np.logspace(start, stop, num)
# Important exception/difference: Unlike np.arange(), logspace() normally includes the stop value.

In [12]:
arr = np.logspace(1, 3, 2) #logarithmic scale array -> 10^1 -> 10^3 ... 2 points
arr

array([  10., 1000.])

In [13]:
# np.zeros() -> creates a NumPy array filled with zeros.
# syntax :- np.zeros(shape, dtype=float)
# Note: dtype is optional, and the default is float.
# Note :- shape ka matlab hai array ka required size/structure. 1D mein number, higher dimensions mein usually tuple.
arr = np.zeros(5)
arr

array([0., 0., 0., 0., 0.])

In [14]:
arr = np.zeros((2,3,4)) #array full of zeros
arr
# 2,3,4 ka matlab 2 blocks → har block mein 3 rows → har row mein 4 elements

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [15]:
# np.ones() -> creates a NumPy array filled with ones.
# np.ones(shape, dtype=float)
# Note :- shape ka matlab hai array ka required size/structure. 1D mein number, higher dimensions mein usually tuple.
# Note: dtype is optional, and the default is float.
arr = np.ones([4, 2])
arr

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [16]:

# np.full() -> creates a NumPy array filled with a specified value.
#syntax :- np.full(shape, fill_value, dtype=None)
arr = np.full(10, 2)
arr

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [17]:
arr = np.full([2,4], 7.1) #[row, column], default value
arr

array([[7.1, 7.1, 7.1, 7.1],
       [7.1, 7.1, 7.1, 7.1]])

In [18]:
# np.empty() -> creates an uninitialized NumPy array of the given shape.
# Syntax:- np.empty(shape, dtype=float)
arr = np.empty([2, 3])
arr

array([[6.83497836e-310, 4.81715546e-315, 0.00000000e+000],
       [1.26801441e-300, 1.39067116e-309, 1.49831070e-195]])

In [19]:
# np.random.rand() -> generates random floating-point numbers between 0 and 1.
# The upper limit 1 is not included.
# Syntax :- np.random.rand(d0, d1, ...)
# d0, d1, ... → dimensions/size of the output array
arr = np.random.rand(10)
arr

array([0.32237719, 0.45921924, 0.54074996, 0.43996826, 0.86767762,
       0.62776246, 0.89066664, 0.35051784, 0.95997623, 0.38540847])

In [20]:
arr = np.random.rand(2,3)
arr

array([[0.01208935, 0.06793141, 0.50803866],
       [0.02635897, 0.07807624, 0.73704661]])

In [21]:
# np.random.randn() -> generates random floating-point numbers
# from a standard normal distribution (mean = 0, standard deviation = 1).
# np.random.randn(d0, d1, ...)
# # d0, d1, ... → dimensions/size of the output array
arr = np.random.randn(2, 3)
arr

array([[ 1.59572564, -0.7485879 , -0.60818929],
       [ 1.01462022,  0.57412934, -1.61149888]])

In [22]:
# np.random.randint() -> generates random integers within a specified range.
# Syntax:- np.random.randint(start, stop, size)
arr = np.random.randint(10, 100, 10)
arr

array([18, 60, 57, 81, 12, 27, 94, 33, 38, 48])

In [23]:
arr = np.random.randint(10, 100, size = (2,3)) #->start, stop, dimension/number of values
arr

array([[97, 72, 62],
       [30, 12, 94]])

## Numpy Data Types and Type Casting

In [24]:
arr = np.array([1,2,3.1,4,5])
arr
#int + float → float

array([1. , 2. , 3.1, 4. , 5. ])

In [25]:
arr.dtype

dtype('float64')

In [26]:
lst = ["string", 1, 2, 5.6]
arr = np.array(lst)
arr

array(['string', '1', '2', '5.6'], dtype='<U32')

In [27]:
arr = np.array(["1",2,3.1,4,5])
arr

array(['1', '2', '3.1', '4', '5'], dtype='<U32')

In [28]:
arr.dtype

dtype('<U32')

In [29]:
arr = np.array([1.1, 2.6 , 3 , 4], dtype = np.int64)

In [30]:
arr.dtype

dtype('int64')

In [31]:
arr

array([1, 2, 3, 4])

In [32]:
#type casting -> astype()

In [33]:
arr = np.array([1,2,3])
arr.dtype

dtype('int64')

In [34]:
# astype() -> converts the elements of an array to a specified data type.
# syntax :- array.astype(dtype)
# array → existing NumPy array
# dtype → desired data type
new_arr = arr.astype(np.float64)

new_arr

array([1., 2., 3.])

In [35]:
new_arr.dtype

dtype('float64')

In [36]:
new_arr2 = new_arr.astype(np.int64)
new_arr2

array([1, 2, 3])

In [37]:
arr = np.array([[1,2,3],
                [4,5,6]])
arr.dtype

dtype('int64')

In [38]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [39]:
arr.ndim

2

In [40]:
arr.shape

(2, 3)

In [41]:
arr.size

6

In [42]:
# itemsize -> returns the number of bytes used by each element of a NumPy array.

arr.itemsize

8

Array Reshaping -> Reshape, Ravel, flatten

In [43]:
# reshape() -> changes the shape of a NumPy array without changing its data.
# array.reshape(new_shape)
# array → existing NumPy array
arr = np.array([1, 2, 3, 4, 5, 6])

reshaped = arr.reshape(2, 3)
print(reshaped)

[[1 2 3]
 [4 5 6]]


In [44]:
reshape2 = reshaped.reshape((3,2))

In [45]:
reshape2

array([[1, 2],
       [3, 4],
       [5, 6]])

In [46]:
# ravel() -> converts a multi-dimensional array into a 1D array.
# syntax :- array.ravel()
# array → existing NumPy array
ravel = reshape2.ravel()

ravel

array([1, 2, 3, 4, 5, 6])

In [47]:
# Note:
# ravel() usually returns a view of the original array instead of a separate copy.
# Therefore, changes made to the raveled array may also affect the original array..
ravel[0] = 100
print(ravel)
print(reshape2)

[100   2   3   4   5   6]
[[100   2]
 [  3   4]
 [  5   6]]


In [146]:
# flatten() -> converts a multi-dimensional array into a 1D array.
# It always returns a copy, so changes to the flattened array
# do not affect the original array.
# Syntax :-
# array.flatten()
# array → existing NumPy array
flat = reshape2.flatten()
flat

array([100,   2,   3,   4,   5,   6])

In [49]:
flat[0] = 1

In [50]:
flat

array([1, 2, 3, 4, 5, 6])

In [51]:
reshape2
# See Reshape change nhi hua hai

array([[100,   2],
       [  3,   4],
       [  5,   6]])

# Arithmetic Operations on Arrays

In [52]:
a = np.array([1,2,3])
b = np.array([4,5,6])


In [53]:
#addition:

print(a+b)

[5 7 9]


In [54]:
# subtraction
print(b-a)

[3 3 3]


In [55]:
#division:
print(a/b)

[0.25 0.4  0.5 ]


In [56]:
# integer division
print(b//a)

[4 2 2]


In [57]:
#multiplication
print(a*b)

[ 4 10 18]


In [58]:
#modulus -> remainder
print(b%a)

[0 1 0]


In [59]:
# exponent -> power
print(a**2)

[1 4 9]


Universal Function -> ufuncs

In [60]:
arr = np.array([1,4,9,16])

In [61]:
# Square root -> np.sqrt()

print(np.sqrt(arr))

[1. 2. 3. 4.]


In [62]:
# exponentioal -> np.exp -> e^x -> x is any integer

print(np.exp([1,2]))

[2.71828183 7.3890561 ]


In [63]:
#sine function -> np.sin

angles = np.array([0, np.pi/2, np.pi])
print(np.sin(angles))

[0.0000000e+00 1.0000000e+00 1.2246468e-16]


In [151]:
# Indexing:- Indexing is used to access one specific element using its position/index.

In [152]:
arr = np.array([10, 20, 30, 40, 50])

arr[2]

np.int64(30)

In [153]:
# Slicing:- Slicing is used to access a range/portion of elements.
# Syntax:-
# array[start:stop:step]
# array is existing numpy array

In [147]:
# When you perform slicing on a NumPy array,
# it returns a new array object that is usually a view of the original array, not an independent copy.

In [148]:
#Array slicing returns a view of a portion of the original array,
# so changes to the slice may affect the original array.

In [149]:
arr = np.array([10, 20, 30, 40, 50])

sliced = arr[1:4]

sliced

array([20, 30, 40])

In [154]:
#When step is negative, slicing moves from right to left. The stop index is still excluded.
a=[10,20,30,40,50]
a[-1:-4:-1]


[50, 40, 30]

In [66]:
a[: :2]

[1, 3, 5]

In [67]:
arr = np.array([10,20,30,40,50])
# indexes = 0, 2, 4
arr[::2]

array([10, 30, 50])

In [68]:
# Negative Indexing
print(arr[-1])

50


In [69]:
matrix = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])

In [70]:
print(matrix[0:2, :])

[[1 2 3]
 [4 5 6]]


In [71]:
print(matrix[1: , 1:])

[[5 6]
 [8 9]]


In [72]:
#np.take -> built in function to perform indexing and slicing
arr = np.array([10,20,30,40,50])
ind = [0,1]
print(np.take(arr, ind))

[10 20]


In [73]:
# Iterating with nditer()
# nditer(existing_array)
#nditer() helps you visit every element one by one even if array has many dimensions.

In [74]:
arr= np.array([[1,2], [3,4]])

In [75]:
for x in np.nditer(arr):
  print(x, end = " ")
# print(x, end=" ")
# x print karo, aur print karne ke baad new line mat do instead ek space do.

1 2 3 4 

In [76]:
# ndenumerate() -> both index + value

for ind, x in np.ndenumerate(arr):
  print(ind, x)



(0, 0) 1
(0, 1) 2
(1, 0) 3
(1, 1) 4


In [77]:
# Views vs Copies

arr = np.array([1,2,3,4,5])
view = arr[1:3]
view

array([2, 3])

In [155]:
# Note:
# Basic NumPy slicing usually returns a view, not a copy.
# Therefore, modifying the slice may affect the original array.

In [78]:
view[0] = 200

In [79]:
view

array([200,   3])

In [80]:
arr

array([  1, 200,   3,   4,   5])

In [81]:
# copy
copy = arr[1:3].copy()
copy

array([200,   3])

In [82]:
copy[0] = 2
copy

array([2, 3])

In [83]:
arr

array([  1, 200,   3,   4,   5])

In [84]:
arr = np.array([[1,2], [3,4]])
arr

array([[1, 2],
       [3, 4]])

In [85]:
print(arr.transpose())

[[1 3]
 [2 4]]


In [86]:
# Swapaxes -> swap 2 specific axes in a matrix.

arr = np.array([[[1,2], [3,4]]])
arr.shape

(1, 2, 2)

In [87]:
swap = np.swapaxes(arr, 0, 1) #
swap.shape
swap

# swap between axix 0 and 1 thats why 1,2,2 se 2,1,2 hua see.

array([[[1, 2]],

       [[3, 4]]])

In [160]:
# Concatenation:

a1 = np.array([1,2])
b1 = np.array([3,4])

In [161]:
combine = np.concatenate((a1,b1))
combine

array([1, 2, 3, 4])

In [90]:
arr1 = np.array([[1,2], [3,4]])
arr2 = np.array([[5,6], [7,8]])

In [91]:
print(np.vstack((arr1, arr2)))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [92]:
print(np.hstack((arr1, arr2)))

[[1 2 5 6]
 [3 4 7 8]]


In [93]:
print(np.stack((arr1, arr2), axis = 0))
# Axis=0 means row kk direction me operate karta hai
# Axis=1 means col kk direction me operate karta hai

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [94]:
print(np.stack((arr1, arr2), axis = 1))

[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]


In [95]:
# Splitting Arrays:
# np.split() -> splits an array into multiple sub-arrays.
# Syntax :-
# np.split(array, sections)
# array is existing numpy array
arr1 = np.array([[1,2], [3,4], [5,6], [7,8]])

In [96]:
arr1

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [97]:
print(np.split(arr1, 4))

[array([[1, 2]]), array([[3, 4]]), array([[5, 6]]), array([[7, 8]])]


In [98]:
print(np.hsplit(arr1, 2))
#np.hsplit() ka matlab hai array ko horizontally split karna, yani columns ke basis par todna.

[array([[1],
       [3],
       [5],
       [7]]), array([[2],
       [4],
       [6],
       [8]])]


In [162]:
# np.repeat() -> repeats each element of an array a specified number of times.
# Syntax:-
# np.repeat(array, repeats)
# array is existing numpy array
arr = np.array([1, 2, 3])

print(np.repeat(arr, 3))

[1 1 1 2 2 2 3 3 3]


In [100]:
# tile -> repeat my whole array

print(np.tile(arr, 2))

[1 2 3 1 2 3]


In [101]:
#Aggregate Functions:

arr = np.array([1,2,3])
print(np.sum(arr))

6


In [102]:
np.mean(arr)

np.float64(2.0)

In [103]:
np.median(arr)

np.float64(2.0)

In [104]:
np.std(arr)

np.float64(0.816496580927726)

In [105]:
np.var(arr)

np.float64(0.6666666666666666)

In [106]:
np.max(arr)

np.int64(3)

In [107]:
np.min(arr)

np.int64(1)

In [108]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [109]:
print(np.sum(matrix, axis = 0))

[12 15 18]


In [110]:
# Cumulative Operations -> running total

arr

array([1, 2, 3])

In [111]:
print(np.cumsum(arr))
#Cummalative Sum:- Har position par us element tak ke saare previous elements ka total.

[1 3 6]


In [112]:
print(np.cumprod(arr))

[1 2 6]


Conditional Based choices


In [163]:
# Where:
# np.where() ka use condition ke basis par values select/replace karne ke liye hota hai.
# np.where(condition, value_if_true, value_if_false)
arr

array([1, 2, 3])

In [114]:
result = np.where(arr <2, "low", "high")

In [115]:
result

array(['low', 'high', 'high'], dtype='<U4')

In [116]:
arr

array([1, 2, 3])

In [165]:
# argwhere: row-column positions for 2d arrays
# np.argwhere() -> returns the indices of elements that satisfy a given condition.
# syntax :- np.argwhere(condition)
# For a 1D array, it returns the indices in a 2D form like [[0], [2], [4]].

In [118]:
arr

array([1, 2, 3])

In [119]:
print(np.argwhere(arr>0))
# condition satisfy hone kk badd index ko return kar deta hai

[[0]
 [1]
 [2]]


In [120]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [121]:
print(np.argwhere(matrix> 5))

[[1 2]
 [2 0]
 [2 1]
 [2 2]]


In [122]:
# Logical and:

arr

array([1, 2, 3])

In [123]:
mask = np.logical_and(arr > 3, arr < 6)

In [124]:
arr[mask]

array([], dtype=int64)

In [125]:
# logical or:

mask = np.logical_or(arr < 4, arr > 5)
mask

array([ True,  True,  True])

In [126]:
arr[mask]

array([1, 2, 3])

In [127]:
arr2 = np.array([0, 1, 5, 0, 5])
arr2

array([0, 1, 5, 0, 5])

In [128]:
print(np.nonzero(arr2))

(array([1, 2, 4]),)


In [129]:
# Broadcasting

In [130]:
image = np.array([[200, 150], [100, 250]])
image.shape

(2, 2)

In [131]:
brightness = image + 50
brightness

array([[250, 200],
       [150, 300]])

In [132]:
# Vectorization:

# np.vectorize() -> convert a regular function to be applied on an array.

In [133]:
def square(x):
  return x*x

vfunc = np.vectorize(square)

In [134]:
arr

array([1, 2, 3])

In [135]:
print(vfunc(arr))

[1 4 9]


In [136]:
# Dealing With Missing values:

# np.nan -> not a number.

In [137]:
a = np.array([1, 2, np.nan, 4])

In [138]:
a

array([ 1.,  2., nan,  4.])

In [139]:
# np.inf and -np.inf -> positive and negative infinites

In [140]:
# np.isnan
# np.isinf
# np.isfinite

# --> these are the functions used to detect any null values, infinte value or fnite value

In [141]:
print(np.isnan(a))

[False False  True False]


In [142]:
b = np.array([1, np.nan, np.inf, 10.2, 40])

In [143]:
print(np.isinf(b))

[False False  True False False]


In [144]:
new_b = np.nan_to_num(b) # remove Nan/ infinite values.

In [145]:
new_b

array([1.00000000e+000, 0.00000000e+000, 1.79769313e+308, 1.02000000e+001,
       4.00000000e+001])